version: '3'
services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
    volumes:
      - /var/lib/rabbitmq

  gateway_api:
    build:
      context: ./
      dockerfile: ./apps/gateway_api/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgresDB
      - rabbitmq
      - chrome
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start gateway_api

  auth_reg:
    build:
      context: ./
      dockerfile: ./apps/auth_reg/Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      - postgresDB
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

  roles:
    build:
      context: ./
      dockerfile: ./apps/roles/Dockerfile
    ports:
      - '3002:3002'
    env_file:
      - .env
    depends_on:
      - postgresDB
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start roles

  postgresDB:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data

  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    privileged: true
    ports:
      - 5900:5900
      - 4444:4444
    shm_size: 2g